url_link = "https://www.saucedemo.com"
usr_nm = "//input[@name = 'user-name']"
pwd = "//input[@id = 'password']"
btn_ln = "//input[@value='Login']"
jacket_cart = "//button[@id='add-to-cart-sauce-labs-fleece-jacket']"
bike_cart = "//button[@id='add-to-cart-sauce-labs-bike-light']"
backpack_cart = "//button[@id='add-to-cart-sauce-labs-backpack']"
shopping_cart_link =  "//a[@class='shopping_cart_link']"
btn_checkout = "//button[@id='checkout']"
first_nm = "//input[@name = 'firstName']"
last_nm = "//input[@name = 'lastName']"
post_code = "//input[@name = 'postalCode']"
btn_continue  = "//input[@id='continue']"
btn_finish = "//button[@id='finish']"
msg_text = "//h2[@class='complete-header']"